set BUILD_TYPE=%1
IF "%BUILD_TYPE%"=="" set BUILD_TYPE=Release

set FTK_API=GL_4_1

set TLRENDER_NET=OFF
set TLRENDER_OCIO=ON
set TLRENDER_JPEG=ON
set TLRENDER_TIFF=ON
set TLRENDER_EXR=ON
set TLRENDER_FFMPEG=ON
set TLRENDER_FFMPEG_MINIMAL=OFF
set TLRENDER_OIIO=ON
set TLRENDER_USD=ON
set TLRENDER_BMD=OFF
set TLRENDER_BMD_SDK=OFF
set TLRENDER_QT6=OFF
set TLRENDER_QT5=OFF
set TLRENDER_PROGRAMS=ON
set TLRENDER_EXAMPLES=ON
set TLRENDER_TESTS=ON
set TLRENDER_GCOV=OFF

tlRender\etc\Windows\windows-build-gha.bat %BUILD_TYPE%
