#!/bin/sh

set -x

BUILD_TYPE=Release
if [ "$#" -eq 1 ]; then
    BUILD_TYPE=$1
fi

export FEATHER_TK_API=GL_4_1
export TLRENDER_NET=OFF
export TLRENDER_FFMPEG=ON
export TLRENDER_FFMPEG_MINIMAL=OFF
export TLRENDER_USD=OFF
export TLRENDER_BMD=OFF
export TLRENDER_BMD_SDK=
export TLRENDER_QT6=OFF
export TLRENDER_QT5=OFF
export TLRENDER_PROGRAMS=ON
export TLRENDER_EXAMPLES=ON
export TLRENDER_TESTS=ON
export TLRENDER_GCOV=OFF
export CMAKE_OSX_DEPLOYMENT_TARGET=10.15
export CMAKE_OSX_ARCHITECTURES=arm64

sh tlRender/etc/macOS/macos-build-gha.sh $BUILD_TYPE
