include(ExternalProject)

set(GLFW_GIT_REPOSITORY "https://github.com/glfw/glfw.git")
set(GLFW_GIT_TAG "901d30b973c536f26b74bca1134c5892d54b251d")

set(GLFW_ARGS
    ${TLR_EXTERNAL_ARGS}
    -DCMAKE_INSTALL_LIBDIR=lib
    -DGLFW_SHARED_LIBS=${BUILD_SHARED_LIBS}
    -DGLFW_BUILD_EXAMPLES=FALSE
    -DGLFW_BUILD_TESTS=FALSE
    -DGLFW_BUILD_DOCS=FALSE)

ExternalProject_Add(
    GLFW
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/GLFW
    GIT_REPOSITORY ${GLFW_GIT_REPOSITORY}
    GIT_TAG ${GLFW_GIT_TAG}
    LIST_SEPARATOR |
    CMAKE_ARGS ${GLFW_ARGS})

