include(ExternalProject)

set(CURL_GIT_REPOSITORY "https://github.com/curl/curl.git")
set(CURL_GIT_TAG "curl-8_3_0")

set(CURL_DEPS)
if(NOT WIN32)
    list(APPEND CURL_DEPS OpenSSL)
endif()
list(APPEND CURL_DEPS ZLIB)

set(CURL_ARGS
    ${TLRENDER_EXTERNAL_ARGS}
    -DCURL_ENABLE_SSL=ON
    -DCURL_USE_OPENSSL=ON
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON)

ExternalProject_Add(
    CURL
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/CURL
    DEPENDS ${CURL_DEPS}
    GIT_REPOSITORY ${CURL_GIT_REPOSITORY}
    GIT_TAG ${CURL_GIT_TAG}
    LIST_SEPARATOR |
    CMAKE_ARGS ${CURL_ARGS})
