include(ExternalProject)

set(tlRender_ARGS
    ${TLRENDER_EXTERNAL_ARGS}
    -DTLRENDER_ENABLE_MMAP=${TLRENDER_ENABLE_MMAP}
	-DTLRENDER_ENABLE_COVERAGE=${TLRENDER_ENABLE_COVERAGE}
    -DTLRENDER_ENABLE_PYTHON=${TLRENDER_ENABLE_PYTHON}
    -DTLRENDER_BUILD_GL=${TLRENDER_BUILD_GL}
    -DTLRENDER_BUILD_QT5=${TLRENDER_BUILD_QT5}
    -DTLRENDER_BUILD_QT6=${TLRENDER_BUILD_QT6}
    -DTLRENDER_BUILD_PROGRAMS=${TLRENDER_BUILD_PROGRAMS}
    -DTLRENDER_BUILD_EXAMPLES=${TLRENDER_BUILD_EXAMPLES}
    -DTLRENDER_BUILD_TESTS=${TLRENDER_BUILD_TESTS})

ExternalProject_Add(
    tlRender
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/tlRender
    DEPENDS ${TLRENDER_EXTERNAL_DEPS}
    SOURCE_DIR ${CMAKE_SOURCE_DIR}/../..
    LIST_SEPARATOR |
    CMAKE_ARGS ${tlRender_ARGS})
