include(ExternalProject)

set(SDL2_GIT_REPOSITORY "https://github.com/libsdl-org/SDL.git")
set(SDL2_GIT_TAG "release-2.30.8")

set(SDL2_ARGS
    ${TLRENDER_EXTERNAL_ARGS}
    -DSDL_STATIC=ON
    -DSDL_DIRECTFB=OFF
    -DSDL_DUMMYVIDEO=OFF
    -DSDL_OPENGL=OFF
    -DSDL_OPENGLES=OFF
    -DSDL_X11=OFF
    -DSDL_WAYLAND=OFF
    -DSDL_RPI=OFF
    -DSDL_COCOA=OFF
    -DSDL_DIRECTX=OFF
    -DSDL_XINPUT=OFF
    -DSDL_RENDER_D3D=OFF
    -DSDL_RENDER_METAL=OFF
    -DSDL_VIVANTE=OFF
    -DSDL_VULKAN=OFF
    -DSDL_METAL=OFF
    -DSDL_KMSDRM=OFF
    -DSDL_HIDAPI=OFF
    -DSDL_VIDEO=OFF
    -DSDL_RENDER=OFF
    -DSDL_JOYSTICK=OFF
    -DSDL_HAPTIC=OFF
    -DSDL_HIDAPI=OFF
    -DSDL_POWER=OFF
    -DSDL_SENSOR=OFF
    -DSDL_LOCALE=OFF)

ExternalProject_Add(
    SDL2
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/SDL2
    GIT_REPOSITORY ${SDL2_GIT_REPOSITORY}
    GIT_TAG ${SDL2_GIT_TAG}
    LIST_SEPARATOR |
    CMAKE_ARGS ${SDL2_ARGS})
