include(ExternalProject)

set(SDL2_GIT_REPOSITORY "https://github.com/libsdl-org/SDL.git")
set(SDL2_GIT_TAG "release-2.0.12")

set(SDL2_PATCH
    ${CMAKE_COMMAND} -E copy_if_different
    ${CMAKE_CURRENT_SOURCE_DIR}/SDL2-patch/CMakeLists.txt
    ${CMAKE_CURRENT_BINARY_DIR}/SDL2/src/SDL2/CMakeLists.txt)

set(SDL2_ARGS
    ${TLRENDER_EXTERNAL_ARGS}
    -DSDL_STATIC_PIC=ON
    -DVIDEO_OPENGL=OFF
    -DVIDEO_OPENGLES=OFF
    -DJACK=OFF
    -DARTS=OFF
    -DNAS=OFF
    -DINPUT_TSLIB=OFF
    -DVIDEO_X11=OFF
    -DVIDEO_WAYLAND=OFF
    -DVIDEO_RPI=OFF
    -DDIRECTX=OFF
    -DRENDER_D3D=OFF
    -DRENDER_METAL=OFF
    -DVIDEO_VIVANTE=OFF
    -DVIDEO_VULKAN=OFF
    -DVIDEO_METAL=OFF
    -DVIDEO_KMSDRM=OFF)

ExternalProject_Add(
    SDL2
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/SDL2
    GIT_REPOSITORY ${SDL2_GIT_REPOSITORY}
    GIT_TAG ${SDL2_GIT_TAG}
    PATCH_COMMAND ${SDL2_PATCH}
    LIST_SEPARATOR |
    CMAKE_ARGS ${SDL2_ARGS})
